name: ci
on:
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: arn:aws:iam::361769556449:root
          role-duration-seconds: 3600 #adjust as needed for your build time
          aws-region: us-east-1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx sst build --stage prod
    - name: Typecheck lambda functions
      run: npm run typecheck
      working-directory: ./packages/functions
